services:
  bot:
    container_name: chimpai_bot
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./voices:/app/voices
      - ./logs:/app/logs
    networks:
      - chimpai-network
    depends_on:
      - valkey

  valkey:
    container_name: chimpai_valkey
    image: valkey/valkey:latest
    restart: always
    networks:
      - chimpai-network
    environment:
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_LOGLEVEL=warning
    volumes:
      - chimpai-valkey-data:/data
      - ./valkey.conf:/etc/valkey/valkey.conf
    command: valkey-server /etc/valkey/valkey.conf

volumes:
  chimpai-valkey-data:

networks:
  chimpai-network:
    driver: bridge
