"""Удалены лишние модели

Revision ID: 334d817bc94b
Revises: 6e98e3fcd6fa
Create Date: 2025-12-30 21:02:13.972812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334d817bc94b'
down_revision: Union[str, None] = '6e98e3fcd6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('settings_id', sa.INTEGER(), nullable=False),
    sa.Column('api_key', sa.VARCHAR(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=255), server_default=sa.text("'https://300.ya.ru/api'"), nullable=False),
    sa.Column('summary_type', sa.VARCHAR(length=10), server_default=sa.text("'detailed'"), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
