"""add base_url

Revision ID: 8ca5fd5ba736
Revises: 42dc81b3e089
Create Date: 2025-06-10 19:53:05.300988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca5fd5ba736'
down_revision: Union[str, None] = '42dc81b3e089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.String(length=255), server_default='https://api.openai.com/v1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('base_url')

    # ### end Alembic commands ###
