name: Telegram Notify
on:
  push:
    branches:
    - master
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Message
      run: |
        msg_text="*Новый коммит в репозитории* ${{ github.repository }}
        *Автор*: ${{ github.actor }}
        *Сообщение*: ${{ github.event.head_commit.message }}
        *SHA*: ${{ github.sha }}
        *Изменения*: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "message_thread_id=${{ secrets.TELEGRAM_TOPIC_ID }}" \
          -d "text=${msg_text}" \
          -d "parse_mode=Markdown" \
          -d "disable_web_page_preview=true"
